services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '80:80'
            - '443:443'
        environment:
            WWWUSER: '1000'
            LARAVEL_SAIL: 1
        volumes:
          - ./lets-encrypt/:/var/www/letsencrypt
          - ./apache2/000-no-ssl-default.conf:/etc/apache2/sites-enabled/000-default.conf
        networks:
            - app-network
        depends_on:
            mysql: 
                condition: service_started
                restart: true

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 'root_password'
            MYSQL_DATABASE: 'rspk_pushaway'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
        volumes:
            - 'mysql-data:/var/lib/mysql'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
